GPU_ID: '0' 
model_restore: 'exp/logs/blackswan/checkpoint_50000' 

test_dir: exp/results/blackswan
dir_video: 'inputs/videos/blackswan' 
dir_mask: 'exp/results/blackswan-mask'


img_shapes: [320, 608]
coarse_only: False 
use_refine: True 
padding: 'SAME'
