GPU_ID: '4' 
model_restore: 'exp/logs/truck-stereo/checkpoint_50000' 

test_dir: exp/results/truck-stereo
dir_video: 'inputs/videos/truck-stereo' 
dir_mask: 'inputs/masks/truck-stereo'


img_shapes: [400, 884]
coarse_only: False 
use_refine: True 
padding: 'SAME'
